# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 397b28a4d9a371361f90248cc99555225916963b73ad7750879a73152a1784b9ef90737437ef010dd854e4bfde9310c04c1111fbd3fdaa2c3ff306bbfd3bec5a

test:
  secret_key_base: c48a3dc3f23396be667159373a94e75fe503f7bc987ca0ac62afc57f2bbda6bb0c878e571c4499e619b06e6f2faf4b072e54f869d47ea64b9d89777325a37556

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
